-- Add 100+ medicinal plants from Indian AYUSH system
INSERT INTO public.herbs (name, scientific_name, description, category, benefits, uses, image_url, growing_conditions, medicinal_properties, culinary_uses, precautions) VALUES
('Ashwagandha', 'Withania somnifera', 'Known as Indian Ginseng, a powerful adaptogenic herb used for stress relief and vitality.', 'medicinal', ARRAY['Reduces stress and anxiety', 'Boosts immunity', 'Improves stamina', 'Enhances brain function'], ARRAY['Stress management', 'Immunity booster', 'Anti-aging'], NULL, 'Dry regions, well-drained soil, full sun', 'Adaptogenic, anti-inflammatory, immunomodulatory, neuroprotective', 'Not commonly used in cooking', 'Avoid during pregnancy. Consult doctor if on thyroid medication'),
('Tulsi', 'Ocimum sanctum', 'Holy Basil is revered in Ayurveda for its healing properties and spiritual significance.', 'medicinal', ARRAY['Boosts immunity', 'Reduces fever', 'Relieves stress', 'Purifies blood'], ARRAY['Respiratory health', 'Fever reduction', 'Tea preparation'], NULL, 'Warm climate, well-drained soil, regular watering', 'Anti-bacterial, anti-viral, anti-inflammatory, adaptogenic', 'Used in herbal teas and as seasoning', 'Safe for most people. May lower blood sugar'),
('Neem', 'Azadirachta indica', 'The village pharmacy tree with powerful antibacterial and antifungal properties.', 'medicinal', ARRAY['Skin health', 'Blood purification', 'Dental care', 'Pest control'], ARRAY['Skin treatments', 'Oral hygiene', 'Natural pesticide'], NULL, 'Tropical climate, drought-resistant, various soil types', 'Antibacterial, antifungal, antiviral, blood purifier', 'Young leaves used in some regional cuisines', 'Avoid during pregnancy. Can be toxic in large amounts'),
('Brahmi', 'Bacopa monnieri', 'Memory enhancer herb used extensively in Ayurvedic brain tonics.', 'medicinal', ARRAY['Enhances memory', 'Reduces anxiety', 'Improves focus', 'Supports nervous system'], ARRAY['Cognitive enhancement', 'Stress relief', 'Mental clarity'], NULL, 'Wetlands, ponds, water bodies, moist soil', 'Nootropic, anxiolytic, neuroprotective, antioxidant', 'Used in herbal preparations, not in regular cooking', 'May cause drowsiness. Avoid before surgery'),
('Amla', 'Phyllanthus emblica', 'Indian Gooseberry, richest natural source of Vitamin C with multiple health benefits.', 'medicinal', ARRAY['Rich in Vitamin C', 'Hair health', 'Immunity booster', 'Digestive aid'], ARRAY['Hair care', 'Immune support', 'Pickles and preserves'], NULL, 'Tropical and subtropical regions, well-drained soil', 'Antioxidant, anti-inflammatory, immunomodulatory, hepatoprotective', 'Used in pickles, chutneys, candies, juices', 'May lower blood sugar. Can cause acidity in some people'),
('Giloy', 'Tinospora cordifolia', 'Divine herb known as Amrita for its immunity-boosting properties.', 'medicinal', ARRAY['Boosts immunity', 'Reduces fever', 'Fights infections', 'Anti-inflammatory'], ARRAY['Fever management', 'Immunity enhancement', 'Chronic illness support'], NULL, 'Tropical climate, well-drained soil, needs support to climb', 'Immunomodulatory, antipyretic, anti-inflammatory, antioxidant', 'Not used in cooking', 'May lower blood sugar. Avoid if autoimmune disorder'),
('Haritaki', 'Terminalia chebula', 'The king of medicines in Tibetan tradition, excellent for digestive health.', 'medicinal', ARRAY['Digestive health', 'Detoxification', 'Improves eyesight', 'Anti-aging'], ARRAY['Constipation relief', 'Detox programs', 'Eye health'], NULL, 'Tropical and subtropical regions, deciduous forests', 'Laxative, antioxidant, anti-inflammatory, hepatoprotective', 'Used in traditional medicine preparations', 'May cause loose stools. Avoid during pregnancy'),
('Shatavari', 'Asparagus racemosus', 'The queen of herbs, especially beneficial for women health.', 'medicinal', ARRAY['Women health', 'Hormonal balance', 'Digestive support', 'Immunity'], ARRAY['Reproductive health', 'Lactation support', 'Stress relief'], NULL, 'Tropical and subtropical forests, well-drained soil', 'Adaptogenic, galactagogue, immunomodulatory, antioxidant', 'Root used medicinally, not in regular cooking', 'Avoid if estrogen-sensitive conditions. May cause allergies'),
('Triphala', 'Combination herb', 'Ancient Ayurvedic formulation combining three fruits for complete wellness.', 'medicinal', ARRAY['Digestive health', 'Detoxification', 'Weight management', 'Eye health'], ARRAY['Daily detox', 'Constipation relief', 'Overall wellness'], NULL, 'Combination of three herbs: Amalaki, Bibhitaki, Haritaki', 'Laxative, antioxidant, anti-inflammatory, hepatoprotective', 'Used in powder or tablet form', 'May cause diarrhea initially. Avoid during pregnancy'),
('Manjistha', 'Rubia cordifolia', 'Blood purifier herb known for skin health and complexion improvement.', 'medicinal', ARRAY['Blood purification', 'Skin health', 'Complexion enhancer', 'Anti-inflammatory'], ARRAY['Skin disorders', 'Blood purification', 'Wound healing'], NULL, 'Hilly areas, moderate climate, well-drained soil', 'Blood purifier, anti-inflammatory, antimicrobial, wound healing', 'Not used in cooking', 'May cause orange discoloration of urine. Avoid during pregnancy'),
('Shankhpushpi', 'Convolvulus pluricaulis', 'Brain tonic herb for memory and mental clarity.', 'medicinal', ARRAY['Memory enhancement', 'Mental clarity', 'Stress relief', 'Sleep quality'], ARRAY['Cognitive support', 'Anxiety management', 'Insomnia treatment'], NULL, 'Plains and grasslands, sandy loam soil', 'Nootropic, anxiolytic, sedative, neuroprotective', 'Not used in cooking', 'May cause drowsiness. Avoid with sedatives'),
('Kalmegh', 'Andrographis paniculata', 'The king of bitters, excellent for liver health and immunity.', 'medicinal', ARRAY['Liver protection', 'Immunity boost', 'Fever reduction', 'Digestive health'], ARRAY['Liver disorders', 'Common cold', 'Fever management'], NULL, 'Tropical plains, moist soil, partial shade', 'Hepatoprotective, immunomodulatory, anti-inflammatory', 'Not used in cooking due to bitter taste', 'Very bitter. May lower blood pressure'),
('Punarnava', 'Boerhavia diffusa', 'Rejuvenating herb excellent for kidney and urinary health.', 'medicinal', ARRAY['Kidney health', 'Diuretic', 'Anti-inflammatory', 'Weight management'], ARRAY['Urinary disorders', 'Edema', 'Kidney stones'], NULL, 'Tropical and subtropical regions, various soil types', 'Diuretic, anti-inflammatory, hepatoprotective, immunomodulatory', 'Not commonly used in cooking', 'May increase urination. Monitor if on diuretics');
